#!/bin/bash
title="Through the Looking-Glass"
subtitle="Mort Yao's homepage"
author_name="Mort Yao"
author_email="soi@mort.ninja"
canonical="https://www.soimort.org/"
id_prefix="tag:www.soimort.org,2016:/"
feed="feed.atom"

feed_updated=`date --iso-8601=seconds`
pandoc_options="--filter monkey.py --filter monkey+.hs --filter qed.hs --filter userParam.hs --filter pandoc-citeproc"

echo """<?xml version=\"1.0\" encoding=\"utf-8\"?>
<feed xmlns=\"http://www.w3.org/2005/Atom\">
  <title>${title}</title>
  <subtitle>${subtitle}</subtitle>
  <link href=\"${canonical}${feed}\" rel=\"self\" />
  <link href=\"${canonical}\" />
  <id>${id_prefix}</id>
  <updated>${feed_updated}</updated>
  <author>
    <name>${author_name}</name>
    <email>${author_email}</email>
  </author>""" > $feed

# generate feed entries
for src in `ls -t */*/src.md`; do
    id=${src%/src.md}

    # skip .archived post (do not create entry)
    if [ -f ${id}/.archived ]; then
        continue
    fi

    # extract metadata (only yaml_metadata_block)
    title=`grep -o -E -m 1 '^title:(.*)' "${src}"`
    title=${title#title: }
    date=`grep -o -E -m 1 '^date-updated:(.*)' "${src}"`
    date=${date#date-updated: }
    if [ -z $date ]; then
        date=`grep -o -E -m 1 '^date:(.*)' "${src}"`
        date=${date#date: }
    fi
    echo `grep -o -E -m 1 '^title:(.*)' "${src}"`
    # pandoc_title_block
    #title=`sed -n '1p' "${src}"`
    #title=${title#% }
    #date=`sed -n '3p' "${src}"`
    #date=${date#% }

    echo """
  <entry>
    <title>${title?-WTF!}</title>
    <link href=\"${canonical}${id}\" />
    <id>${id_prefix}${id}</id>
    <updated>${date?-WTF!}</updated>
    <author>
      <name>${author_name}</name>
      <email>${author_email}</email>
    </author>
    <content type=\"xhtml\">
      <div xmlns=\"http://www.w3.org/1999/xhtml\">
""" >> $feed
    pandoc -t html ${pandoc_options} "${src}" >> $feed
    echo """
      </div>
    </content>
  </entry>""" >> $feed
done

echo """
</feed>""" >> $feed
